#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
WAVE1_PLAN="${WAVE1_PLAN:-plans/exploratory-wave1.jsonl}"
WAVE2_PLAN="${WAVE2_PLAN:-plans/exploratory-wave2.jsonl}"
WAVE1_ARRAY="0-61%2"
WAVE2_ARRAY="0-31%2"

cd "${PROJECT_ROOT}"
unset LD_LIBRARY_PATH
unset VIRTUAL_ENV
source "${VENV_ACTIVATE:-.venv/bin/activate}"
export PYTHONPATH="${PROJECT_ROOT}/src${PYTHONPATH:+:${PYTHONPATH}}"
mkdir -p "$(dirname -- "${WAVE1_PLAN}")"

python -m optimizer_resurrection.experiment plan \
  configs/exploratory/smoke_mlp_2xl40s.yaml \
  configs/exploratory/smoke_rnn_2xl40s.yaml \
  configs/exploratory/gates_2xl40s.yaml \
  configs/exploratory/lr_scout_2xl40s.yaml \
  --plan-file "${WAVE1_PLAN}" >/dev/null

WAVE1_RUNS="$(wc -l < "${WAVE1_PLAN}")"
if [[ "${WAVE1_RUNS}" -ne 62 ]]; then
  echo "Expected 62 wave-one commands, found ${WAVE1_RUNS}" >&2
  exit 1
fi

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  echo "DRY_RUN=1"
  echo "Project root: ${PROJECT_ROOT}"
  echo "Wave 1 plan: ${WAVE1_PLAN} (${WAVE1_RUNS} runs)"
  echo "Wave 1 array: ${WAVE1_ARRAY}"
  echo "Recipe selection: afterok wave 1 (CPU only)"
  echo "Wave 2 plan: ${WAVE2_PLAN} (generated by recipe selection)"
  echo "Wave 2 array: ${WAVE2_ARRAY}"
  echo "Maximum simultaneous GPU tasks: 2"
  echo "Submit wave 1: sbatch --parsable --array=${WAVE1_ARRAY} scripts/oscar_plan.sbatch ${WAVE1_PLAN}"
  echo "Submit selection: sbatch --parsable --dependency=afterok:<wave1> scripts/oscar_select_exploratory.sbatch"
  echo "Submit wave 2: sbatch --parsable --dependency=afterok:<selection> --array=${WAVE2_ARRAY} scripts/oscar_plan.sbatch ${WAVE2_PLAN}"
  exit 0
fi

WAVE1_SUBMISSION="$(sbatch --parsable --array="${WAVE1_ARRAY}" scripts/oscar_plan.sbatch "${WAVE1_PLAN}")"
WAVE1_JOB_ID="${WAVE1_SUBMISSION%%;*}"
SELECT_SUBMISSION="$(sbatch --parsable --dependency="afterok:${WAVE1_JOB_ID}" scripts/oscar_select_exploratory.sbatch)"
SELECT_JOB_ID="${SELECT_SUBMISSION%%;*}"
WAVE2_SUBMISSION="$(sbatch --parsable --dependency="afterok:${SELECT_JOB_ID}" --array="${WAVE2_ARRAY}" scripts/oscar_plan.sbatch "${WAVE2_PLAN}")"
WAVE2_JOB_ID="${WAVE2_SUBMISSION%%;*}"

echo "Wave 1 job: ${WAVE1_JOB_ID}"
echo "Recipe-selection job: ${SELECT_JOB_ID}"
echo "Wave 2 job: ${WAVE2_JOB_ID}"
echo "Maximum simultaneous GPU tasks: 2"
