#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-/users/ezhan153/random-idea-1}"
export PROJECT_ROOT
WAVE1_PLAN="${WAVE1_PLAN:-plans/exploratory-wave1.jsonl}"
WAVE2_PLAN="${WAVE2_PLAN:-plans/exploratory-wave2.jsonl}"
SMOKE_ARRAY="0-7%2"
EXPLORATORY_ARRAY="8-61%2"
WAVE2_ARRAY="0-31%2"
PHASE="${1:-}"
UV_BIN="${UV_BIN:-}"
if [[ -z "${UV_BIN}" && -x "${PROJECT_ROOT}/.uv-bootstrap/bin/uv" ]]; then
  UV_BIN="${PROJECT_ROOT}/.uv-bootstrap/bin/uv"
fi
if [[ -z "${UV_BIN}" ]]; then
  UV_BIN="$(command -v uv || true)"
fi

if [[ "${PHASE}" != "smoke" && "${PHASE}" != "exploratory" ]]; then
  echo "Usage: bash scripts/oscar_submit_exploratory.sh smoke|exploratory" >&2
  exit 2
fi

cd "${PROJECT_ROOT}"
unset LD_LIBRARY_PATH
unset VIRTUAL_ENV
if [[ -z "${UV_BIN}" || ! -x "${UV_BIN}" ]]; then
  echo "uv is unavailable; provision the locked Oscar environment first" >&2
  exit 1
fi
export PYTHONPATH="${PROJECT_ROOT}/src${PYTHONPATH:+:${PYTHONPATH}}"
mkdir -p "$(dirname -- "${WAVE1_PLAN}")"

"${UV_BIN}" run --frozen --no-sync python -m optimizer_resurrection.experiment plan \
  configs/exploratory/smoke_mlp_2xl40s.yaml \
  configs/exploratory/smoke_rnn_2xl40s.yaml \
  configs/exploratory/gates_2xl40s.yaml \
  configs/exploratory/lr_scout_2xl40s.yaml \
  --plan-file "${WAVE1_PLAN}" >/dev/null

WAVE1_RUNS="$(wc -l < "${WAVE1_PLAN}")"
if [[ "${WAVE1_RUNS}" -ne 62 ]]; then
  echo "Expected 62 wave-one commands, found ${WAVE1_RUNS}" >&2
  exit 1
fi

bash -n scripts/oscar_plan.sbatch
bash -n scripts/oscar_select_exploratory.sbatch

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  echo "DRY_RUN=1"
  echo "Project root: ${PROJECT_ROOT}"
  echo "Wave 1 plan: ${WAVE1_PLAN} (${WAVE1_RUNS} total commands)"
  echo "Phase: ${PHASE}"
  echo "Maximum simultaneous GPU tasks: 2"
  if [[ "${PHASE}" == "smoke" ]]; then
    echo "Smoke array: ${SMOKE_ARRAY}"
    echo "Submit smoke: sbatch --parsable --array=${SMOKE_ARRAY} scripts/oscar_plan.sbatch ${WAVE1_PLAN}"
  else
    echo "Exploratory array: ${EXPLORATORY_ARRAY}"
    echo "Recipe selection: afterok exploratory array (CPU only)"
    echo "Wave 2 plan: ${WAVE2_PLAN} (generated by recipe selection)"
    echo "Wave 2 array: ${WAVE2_ARRAY}"
    echo "Submit exploratory: sbatch --parsable --array=${EXPLORATORY_ARRAY} scripts/oscar_plan.sbatch ${WAVE1_PLAN}"
    echo "Submit selection: sbatch --parsable --dependency=afterok:<exploratory> scripts/oscar_select_exploratory.sbatch"
    echo "Submit wave 2: sbatch --parsable --dependency=afterok:<selection> --array=${WAVE2_ARRAY} scripts/oscar_plan.sbatch ${WAVE2_PLAN}"
  fi
  exit 0
fi

if [[ "${PHASE}" == "smoke" ]]; then
  sbatch --test-only --array="${SMOKE_ARRAY}" scripts/oscar_plan.sbatch "${WAVE1_PLAN}"
  SMOKE_SUBMISSION="$(sbatch --parsable --array="${SMOKE_ARRAY}" scripts/oscar_plan.sbatch "${WAVE1_PLAN}")"
  SMOKE_JOB_ID="${SMOKE_SUBMISSION%%;*}"
  echo "Smoke job: ${SMOKE_JOB_ID}"
  echo "Maximum simultaneous GPU tasks: 2"
  exit 0
fi

if [[ "${SMOKE_VERIFIED:-0}" != "1" ]]; then
  echo "Set SMOKE_VERIFIED=1 only after the smoke W&B group is verified and deleted." >&2
  exit 1
fi

sbatch --test-only --array="${EXPLORATORY_ARRAY}" scripts/oscar_plan.sbatch "${WAVE1_PLAN}"
sbatch --test-only scripts/oscar_select_exploratory.sbatch
sbatch --test-only --array="${WAVE2_ARRAY}" scripts/oscar_plan.sbatch "${WAVE2_PLAN}"
EXPLORATORY_SUBMISSION="$(sbatch --parsable --array="${EXPLORATORY_ARRAY}" scripts/oscar_plan.sbatch "${WAVE1_PLAN}")"
EXPLORATORY_JOB_ID="${EXPLORATORY_SUBMISSION%%;*}"
SELECT_SUBMISSION="$(sbatch --parsable --dependency="afterok:${EXPLORATORY_JOB_ID}" scripts/oscar_select_exploratory.sbatch)"
SELECT_JOB_ID="${SELECT_SUBMISSION%%;*}"
WAVE2_SUBMISSION="$(sbatch --parsable --dependency="afterok:${SELECT_JOB_ID}" --array="${WAVE2_ARRAY}" scripts/oscar_plan.sbatch "${WAVE2_PLAN}")"
WAVE2_JOB_ID="${WAVE2_SUBMISSION%%;*}"

echo "Exploratory job: ${EXPLORATORY_JOB_ID}"
echo "Recipe-selection job: ${SELECT_JOB_ID}"
echo "Wave 2 job: ${WAVE2_JOB_ID}"
echo "Maximum simultaneous GPU tasks: 2"
